version: '3'

services:
  app:
    image: 'todowithreact'
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      dbpostgre:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgre:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - db-network
          
  dbpostgre:
    image: 'postgres'
    container_name: dbpostgre
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      retries: 1

networks:
  db-network:
    driver : bridge
